yarnPath: .yarn/releases/yarn-3.1.0.cjs
nodeLinker: pnp
packageExtensions:
  "@mui/core@*":
    dependencies:
      "@mui/system": "*"
  "@mui/styled-engine@*":
    dependencies:
      "@emotion/react": "*"
      "@emotion/styled": "*"
